In [61]:
import tensorflow as tf

In [62]:
#pembuatan variabel random tensor
random_tensor = tf.random.normal(shape=[5,5], mean=0, stddev=1, seed=1)#penggunan tf.random yang nilainya random
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.02631566,  0.59973025,  2.1930096 ,  0.70548636, -0.15317097],
       [-0.87380695, -0.41602153,  0.10885387, -0.30898607, -0.08477694],
       [-1.4043791 ,  0.3359162 , -0.5440277 , -0.6701393 , -1.1809127 ],
       [-1.1672325 ,  1.168095  , -0.6827249 ,  1.2158072 ,  0.6584982 ],
       [ 0.20425868,  0.07945652,  0.07206825, -0.4303542 , -0.32767358]],
      dtype=float32)>

In [63]:
#Melihat dimensi
random_tensor.shape

TensorShape([5, 5])

In [64]:
#pembuatan variabel prime tensor
Prime_tensor = tf.Variable(tf.ones([5,5]))
Prime_tensor.read_value()
var_value_1 = [[2,3,5,7,11],[13,17,19,23,19],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]
Prime_tensor.assign(var_value_1)
Prime_tensor.read_value()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 19.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

In [65]:
#melihat dimensi
Prime_tensor.shape

TensorShape([5, 5])

In [66]:
#Oprataor penjumlahan
a = random_tensor
b = Prime_tensor
print(tf.add(a,b))

tf.Tensor(
[[ 2.0263157  3.5997303  7.1930094  7.7054863 10.846829 ]
 [12.126193  16.583979  19.108854  22.691013  18.915222 ]
 [29.595621  37.335915  40.45597   42.32986   45.819088 ]
 [51.832767  60.168095  60.317276  68.215805  71.6585   ]
 [73.20426   79.07946   83.07207   88.56965   96.672325 ]], shape=(5, 5), dtype=float32)


In [67]:
#Oprator Pengurangan
a = random_tensor
b = Prime_tensor
print(tf.subtract(a,b))

tf.Tensor(
[[ -1.9736843  -2.4002697  -2.8069904  -6.2945137 -11.153171 ]
 [-13.873807  -17.416021  -18.891146  -23.308987  -19.084778 ]
 [-32.40438   -36.664085  -41.54403   -43.67014   -48.180912 ]
 [-54.167233  -57.831905  -61.682724  -65.784195  -70.3415   ]
 [-72.79574   -78.92054   -82.92793   -89.43035   -97.327675 ]], shape=(5, 5), dtype=float32)


In [68]:
#Oprator Perkalian
a = random_tensor
b = Prime_tensor
print(tf.multiply(a,b))

tf.Tensor(
[[ 5.2631319e-02  1.7991908e+00  1.0965048e+01  4.9384046e+00
  -1.6848807e+00]
 [-1.1359490e+01 -7.0723658e+00  2.0682235e+00 -7.1066794e+00
  -1.6107619e+00]
 [-4.3535751e+01  1.2428899e+01 -2.2305136e+01 -2.8815990e+01
  -5.5502899e+01]
 [-6.1863323e+01  6.8917603e+01 -4.1646217e+01  8.1459084e+01
   4.6753376e+01]
 [ 1.4910884e+01  6.2770653e+00  5.9816647e+00 -3.8301525e+01
  -3.1784338e+01]], shape=(5, 5), dtype=float32)


In [69]:
#Oprator Pembagian
a = random_tensor
b = Prime_tensor
print(tf.divide(a,b))

tf.Tensor(
[[ 0.01315783  0.19991009  0.4386019   0.10078377 -0.01392463]
 [-0.06721592 -0.02447185  0.00572915 -0.01343418 -0.00446194]
 [-0.04530255  0.00907882 -0.01326897 -0.01558464 -0.0251258 ]
 [-0.02202326  0.01979822 -0.01119221  0.01814638  0.00927462]
 [ 0.00279806  0.00100578  0.00086829 -0.00483544 -0.00337808]], shape=(5, 5), dtype=float32)


In [70]:
#oprator Pangkat
a = random_tensor
b = Prime_tensor
print(tf.pow(a,b))

tf.Tensor(
[[ 6.9251395e-04  2.1570881e-01  5.0722736e+01  8.6980186e-02
  -1.0887826e-09]
 [-1.7314161e-01 -3.3494126e-07  5.0122596e-19 -1.8560713e-12
  -4.3378729e-21]
 [-3.7326336e+04  2.9549129e-18 -1.4469752e-11 -3.3504190e-08
  -2.4787734e+03]
 [-3.6252749e+03  9.5766045e+03 -7.7444398e-11  4.8521656e+05
   1.3103199e-13]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 -2.5734679e-33
  -0.0000000e+00]], shape=(5, 5), dtype=float32)


In [71]:
#Melihat nilai max dari variabel random tensor
tf.argmax(random_tensor, axis=0).numpy()

array([4, 3, 0, 3, 3], dtype=int64)

In [72]:
#Melihat nilai min dari variabel random tensor
tf.argmin(random_tensor, axis=0).numpy()

array([2, 1, 3, 2, 2], dtype=int64)

In [73]:
#Menggabungkan variabel random tensor dan prime tensor
merge = tf.concat([random_tensor, Prime_tensor], axis=0)#untuk kolom 0 kalau baris 1
merge

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 2.6315659e-02,  5.9973025e-01,  2.1930096e+00,  7.0548636e-01,
        -1.5317097e-01],
       [-8.7380695e-01, -4.1602153e-01,  1.0885387e-01, -3.0898607e-01,
        -8.4776938e-02],
       [-1.4043791e+00,  3.3591619e-01, -5.4402769e-01, -6.7013931e-01,
        -1.1809127e+00],
       [-1.1672325e+00,  1.1680950e+00, -6.8272489e-01,  1.2158072e+00,
         6.5849823e-01],
       [ 2.0425868e-01,  7.9456523e-02,  7.2068252e-02, -4.3035421e-01,
        -3.2767358e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         1.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

In [74]:
#Sorting Descending variabel random tensor
sort= tf.sort(random_tensor, direction="DESCENDING")
print("Sebelum disorting : ", random_tensor.numpy())
print("Setelah di sorting Descending : ",sort)

Sebelum disorting :  [[ 0.02631566  0.59973025  2.1930096   0.70548636 -0.15317097]
 [-0.87380695 -0.41602153  0.10885387 -0.30898607 -0.08477694]
 [-1.4043791   0.3359162  -0.5440277  -0.6701393  -1.1809127 ]
 [-1.1672325   1.168095   -0.6827249   1.2158072   0.6584982 ]
 [ 0.20425868  0.07945652  0.07206825 -0.4303542  -0.32767358]]
Setelah di sorting Descending :  tf.Tensor(
[[ 2.1930096   0.70548636  0.59973025  0.02631566 -0.15317097]
 [ 0.10885387 -0.08477694 -0.30898607 -0.41602153 -0.87380695]
 [ 0.3359162  -0.5440277  -0.6701393  -1.1809127  -1.4043791 ]
 [ 1.2158072   1.168095    0.6584982  -0.6827249  -1.1672325 ]
 [ 0.20425868  0.07945652  0.07206825 -0.32767358 -0.4303542 ]], shape=(5, 5), dtype=float32)


In [75]:
#Sorting Descending Variabel Prime tensor
sort1= tf.sort(Prime_tensor, direction="DESCENDING")
print("Sebelum disorting : ", Prime_tensor.numpy())
print("Setelah di sorting Descending : ",sort1)

Sebelum disorting :  [[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 19.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]]
Setelah di sorting Descending :  tf.Tensor(
[[11.  7.  5.  3.  2.]
 [23. 19. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
